Create NiceHexSpiral.py
This is what happened when I tried to run it in the interactive terminal, because I forgot about whitespace in the for loop:

>>> import turtle
>>> colors = ['red','purple','blue','green','yellow','orange']
>>> t=turtle.Pen()
>>> turtle.bgcolor('black')
>>> for x in range(360) :
... t.pencolor(colors[x%6])
  File "<stdin>", line 2
    t.pencolor(colors[x%6])
    ^
IndentationError: expected an indented block
>>> for x in range(360) :
...   t.pencolor(colors[x%6])
...   t.width(x/100+1)
...   t.forward(x)
...   t.left(59)